name: issue-translator

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
    
jobs:
  build:
    runs-on: [self-hosted, Linux, dev-runner]
    steps:
      - run: echo "Good one"
